stages:
  - build
  - publish

#############################################
# Stage: build                              #
#############################################
Build:
  stage: build
  image: opentapio/opentap:9.7-ubuntu18.04
  tags: [ docker, gce ]
  script:
    - apt install locales locales-all
    - dotnet publish SshSteps.sln -c Release
  artifacts:
    expire_in: 1 day
    paths:
       - bin/

#############################################
# Stage: publish                            #
#############################################
Publish:
  stage: publish
  image: opentapio/opentap:9.7-slim-ubuntu18.04
  tags: [ docker, gce ]
  only:
    - tags
    - /^release.*$/
    - master
  dependencies:
    - Build
  script:
    - tap package install PackagePublish
    - tap package publish -k $REPO_PUBLISH_KEY -r packages.opentap.io bin/Release/Ssh.*.TapPackage